apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srejectroot
spec:
  crd:
    spec:
      names:
        kind: K8sRejectRoot
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srejectroot
        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          c.securityContext.privileged
          msg := sprintf("Privileged container is not allowed: %v, securityContext: %v", [c.name, c.securityContext])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRejectRoot
metadata:
  name: pod-reject-root
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]